version: '3.10'

services:
  app:
    image: lab1sysprog
    build: 
     context: ./
     dockerfile: ./application/Dockerfile
    volumes:
      - ./source/:/Project/source/
    stdin_open: true
    tty: true
